### ISSUE TITLE
"[Errno 13] Permission denied" & "Can't initialize prompt toolkit" Errors

### ISSUE THREAD

**Issue by adunato** [p-wegner/coding-aider#42]
After installing the plugin I hit "Test Aider Installation" and get the following. 

```
Warning: Unable to write to chat history file .aider.chat.history.md.
[Errno 13] Permission denied: '.aider.chat.history.md'
Can't initialize prompt toolkit: No Windows console found. Are you running 
cmd.exe?

```
The "Coding Aider" window allows me to add files to the context (although these are not picked up by aider in terminal) and nothing else.

The "Aider Command" window sees the context and allows entering a prompt but generates the following error:
```
Can't initialize prompt toolkit: No Windows console found. Are you running cmd.exe? ─────────────────────────────────────────────────────────────────────────────── Aider v0.67.0 Main model: claude-3-5-sonnet-20241022 with diff edit format, infinite output Weak model: claude-3-5-haiku-20241022 Git repo: .git with 167 files Repo-map: using 1024 tokens, auto refresh ───────────────────────────────────────────────────────────────────────────────
```

**Comment by adunato** [comment]
Aider v0.67.0 is installed and can be reached by any cmd shell.

**Comment by p-wegner** [comment]
Hi, thank you for trying the plugin. 
It seems like your IDE doesn't start with sufficient permissions (and therefore aider which is started as a subprocess) to create .aider.chat.history.md in the project root folder. To avoid this issue you can start aider in the project folder once and prompt it any prompt, so aider will create its history and input markdown files. If this solves the issue, let me know.

**Comment by p-wegner** [comment]
Currently there is a bug in the plugin that prevents it from adding some aider arguments like --no-fancy-input or --no-pretty when you leave the llm selection dropdown empty. So you could try to select --sonnet explicitely. I plan to release a version with a fix for this in the coming days.

I've seen the error when trying to script with aider from a crewai python app and opened https://github.com/Aider-AI/aider/issues/1244 then. My assumption is that ultimately its caused by aiders usage of the prompt toolkit library, which sometimes prevents scriptability when running aider without using a pseudoterminal. Some of aiders custom options seem to solve this.
Other projects that use the library face similar issues https://github.com/xyb/robotframework-debuglibrary/issues/72 with this root issue
https://github.com/prompt-toolkit/python-prompt-toolkit/issues/406
and aider has reoccuring issues, that seem to be related, see https://github.com/Aider-AI/aider/issues?q=is%3Aissue+NoConsoleScreenBufferError
Without a way to reproduce the error I can't give you more helpful answer and hope my fix will be enough to solve this for you.

**Comment by adunato** [comment]
Thanks for getting back to me. Adding a default model works, so thanks for that!
