### ISSUE TITLE
Plugin does not detect aider for me

### ISSUE THREAD

**Issue by misrasaurabh1** [p-wegner/coding-aider#48]
Hi,

I wanted a plugin for aider for Pycharm so wanted to try this out. Unfortunately i haven't been able to make it work successfully on my IDE.

Attaching a 30 second video showing what is happening, maybe you can help me figure out what is wrong.
 https://www.loom.com/share/6c90a16d79c04facbd33d0dd6efda7c5?sid=3b74a988-2ec8-4615-8114-b3413fa46dd0

**Comment by p-wegner** [comment]
Hi Saurabh,

thank you for trying the plugin and giving feedback. Since you are running Mac OS, it's likely to be a variant of https://github.com/p-wegner/coding-aider/issues/40. You could try setting the path to aider in the settings manually as a workaround until i find a better solution and let me know if that helps.

**Comment by misrasaurabh1** [comment]
Thanks! This solved my issue. Although looking at the "Aider Executable Path" option, it did not seem like it was editable and hence it missed it.
